version: '3.7'
services:
  database:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: local_dev
      POSTGRES_USER: local_dev
      POSTGRES_DB: local_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: